### ISSUE TITLE
Feld "Ort" nach Import in eigenen Kalender leer

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/rrze-calendar#110]
Abonniere ich einen Termin und speichere ihn in meinem Kalender ist das in Outlook ausgefüllte Feld "Ort" leer. 

Beispiel: https://www.fau.de/termine/wissenwollen-wie-in-der-oper-emotionen-ausgedrueckt-und-erlebt-werden/

Nutzer:innen sollen durch Klick auf das Kartensymbol in ihrem Kalender neben der Ortsangabe direkt zu Naviapp kommen um ihr Ziel leichter zu finden.

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.

**Comment by cassandre** [comment]
In der neuen Version gefixt.
