### ISSUE TITLE
Button "Abonnieren" umbenennen

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/rrze-calendar#111]
Button "Abonnieren" umbenennen in gängigeres "Zum Kalender hinzufügen".

Nutzer:innen sollen besser verstehen, wozu der Button da ist und animiert werden ihn zu klicken.

Beispiel: https://www.fau.de/termine/wissenwollen-wie-in-der-oper-emotionen-ausgedrueckt-und-erlebt-werden/

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
