### ISSUE TITLE
Layout beim Button "Abonnement" stimmt nicht

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-calendar#113]
main .rrze-calendar.events-list a, main .rrze-calendar.kalender a

setzt offenbar "color" und "padding". 

Werden sie über die DevTools des Browsers ausgeschaltet, stimmt das Layout wieder. 

![Bildschirmfoto 2022-07-08 um 16 50 45](https://user-images.githubusercontent.com/54806119/178016727-c66bacf4-0bc0-4571-9703-f577a8020375.png)

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
