### ISSUE TITLE
Button Abonnieren fehlt

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-calendar#114]
Bei der Darstellung als Kalenderansicht fehlt der Button "Abonnieren", auch wenn der shortcode [kalender kategorien="..." abonnement_link="1"] angegeben ist. Bei [termine kategorien="..." abonnement_link="1"] funktioniert der Button (auch wenn der Button farblich sehr schlecht lesbar ist, schwarze Schrift auf dunkelgrün). Kann man das bitte auch für die Kalenderdarstellung aktivieren? Vor allem bei unseren vielen Gremiensitzungen ist es sinnvoll die Kalenderdarstellung anzuzeigen, weil es übersichtlicher ist.

**Comment by xwolfde** [comment]
Bitte eine URL als Angabe zum prüfen.

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
