### ISSUE TITLE
Anzeige der "Kalenderblätter"

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-calendar#135]
Seite https://www.fau.de/newsportal/ ganz unten: Die Höhe und Breite der Kalenderblätter ist nicht einheitlich...
<img width="751" alt="image" src="https://github.com/RRZE-Webteam/rrze-calendar/assets/9526974/f2f4eb7a-c27e-48b0-a7d2-4af99c2248fb">

**Comment by cassandre** [comment]
Ist mittlerweile gefixt.
