### ISSUE TITLE
Parameter page_link= 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#14]
fau-events hatte noch einen Parameter

   page_link="1129625"

für den SHortcode. Als Id konnte man hier die Id einer Seite angeben, die man dann verlinkt hat. Dies fehlt hier?

**Comment by rvdforst** [comment]
Ich habe das "page_link"-Attribute hinzugefügt. Siehe https://github.com/RRZE-Webteam/rrze-calendar/commit/664a2a8471d2d4f92d6bf0a488822b3a1450599d und https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/6fb45451a12286627e20f6ecc52bfd6a3f0dc9bd
