### ISSUE TITLE
Class für Farbe bzw CI-farbe von Fakultäten und span satt div bei zusammenhängenden Daten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#15]
Hier bitte was ändern:

```
<div class="event-detail-item">

   <div class="event-date" style="background-color: "> 
      <div class="event-date-month"> Sep </div>
      <div class="event-date-day"> 28 </div>   
   </div>
...
```

1. Hier fehlt die gewählte Farbe.
Wenn es eine CI-Farbe ist, dann wäre es gut,w enn hier kein Inlinestyle ist, sondern dies mit der Klasse gemacht wird.
Und zwar in dem fall so:

`<div class="event-date phil"> `

Default Farbklassen der CI dürfen sein:  tf, phil, nat, med, rw, fau
   
Wenn keine Farbe gewählt ist, bitte keine Klasse setzen und auch keinen style="".
Den Style= nur setzen, wenn man eine eigene neu Farbe wählte.

2. Statt
 ```
 <div class="event-date-month"> Sep </div>
      <div class="event-date-day"> 28 </div>   
```
Lieber dort nur span nehmen:
`<span class="event-date-month"> Sep </span> <span class="event-date-day"> 28 </span>   `

**Comment by rvdforst** [comment]
Ist erledigt. Siehe https://github.com/RRZE-Webteam/rrze-calendar/commit/1b0a2e663bca38087eb69a9500a2bb2be581c21d.
Die entsprechenden FAU-Einrichtungen-Templates wurden auch angepasst.
