### ISSUE TITLE
Gestaltungselemente aus Elements in Kalendereinträgen

### ISSUE THREAD

**Issue by zfl-ulrike** [RRZE-Webteam/rrze-calendar#152]
Wäre es vielleicht denkbar, dass man in den Beschreibungen der Kalendereinträge Shortcodes aus dem Elements-PlugIn z. B. Buttons oder LimitWidth verwenden kann?

**Comment by cassandre** [comment]
In e5e20cf35ad2d50ee62563a24da5171c8f828374 ergänzt; ist im nächsten Update drin.
