### ISSUE TITLE
wrap in Sidebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#159]
Der wrap der Inhalte (vorallem in der SIdebar erscheint mir ungünstig.
<img width="692" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-calendar/assets/1070669/0c4552e7-7316-4163-82f6-0db84b9d78f2">

ggf. hier ein besseren Textwrap einfügen;  Vorschlag:

```
.event-location {
  word-wrap: anywhere;
}

```

**Comment by cassandre** [comment]
In a440cd7 gefixt
