### ISSUE TITLE
class="event-detail-item"

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#16]
Die Klasse event-detail-item darf nur gesetzt werden, wenn ein Einzeltermin angezeigt wird. Also bei der Single-Ansicht.
Nicht bei der Liste aller. Da bitte einfach diese Kalsse weglassen.

**Comment by rvdforst** [comment]
Fehler beseitigt. Siehe https://github.com/RRZE-Webteam/rrze-calendar/commit/d2eb5048e97426f2a910011ba944e5e5d99f905d
