### ISSUE TITLE
Ganztägige Termine werden falsch dargestellt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-calendar#161]
Aus http://go.fau.de/9vie4

wir haben im Moment das Problem, das Veranstaltungen, die sich über mehrere Tage erstrecken, so nicht unter den Terminen auf der Website angezeigt werden. Beispielsweise findet die „9th International Conference on Discrete Element Methods“ von Sonntag, 17.09.23, 18:30 Uhr, bis Donnerstag, 21.09.23, 17:30 Uhr statt. Tatsächlich wird aber seit heute (seitdem wir den davon unabhängigen Termin für die School of Adsorption eingefügt haben) nur der 17.09.23 mit falschen Uhrzeiten angezeigt: https://www.cbi.tf.fau.de/

![Bildschirmfoto 2023-08-16 um 16 08 48](https://github.com/RRZE-Webteam/rrze-calendar/assets/58593037/ebb791cf-fd1a-40cf-afc8-d4cfbb428b5a)

ICS-Feed: https://groupware.fau.de/owa/calendar/9d0a6c2291444553ae145f31f357c891@fau.de/994ee72ef4444888bba618ddcf4e78379006933513381097254/calendar.html

**Comment by cassandre** [comment]
gefixt in 79e23bc
