### ISSUE TITLE
Veranstaltungen werden mehrmals dargestellt, obwohl nur ein Eintrag existiert

### ISSUE THREAD

**Issue by TFWebm** [RRZE-Webteam/rrze-calendar#164]
Auf der Seite der TF werden Veranstaltungen mehrmals dargestellt, obwohl im Backend nur ein Eintrag existiert:
https://www.tf.fau.de/veranstaltungen-tf/
![grafik](https://github.com/RRZE-Webteam/rrze-calendar/assets/25925645/b58d5ee9-d3c8-476a-a22c-c18b0360fe06)

Die URLs reichen bei einem Beispiel bis 7:
https://www.tf.fau.de/events/interdisciplinary-hand-symposium-7/
https://www.tf.fau.de/events/interdisciplinary-hand-symposium-6/
...
https://www.tf.fau.de/events/interdisciplinary-hand-symposium/

**Comment by cassandre** [comment]
Diese Veranstaltungen sind jeweils identisch in unterschiedlichen Feeds eingetragen (Backend > Kalender > Veranstaltungen => nach "Interdisciplinary" suchen => die rechte Spalte zeigt die Feed-Quelle an).

Für die Darstellung einer einzelnen Kategorie müssen alle Events erhalten bleiben.
Bei einer Darstellung mehrerer Kategorien, müssen Duplikate erkannt und entfernt werden. Welches Event welcher Kategorie  (und damit ggf. welcher Farbe) angezeigt wird, kann nur relativ willkürlich entschieden werden.
