### ISSUE TITLE
Automatisches Löschen von vergangenen Veranstaltungen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-calendar#166]
Momentan werden vergangene Veranstaltungen weder gelöscht noch sonst offline genommen. Theoretisch sind sie weiterhin über einen Link aufrufbar - und sie bleiben natürlich auch im Backend.

Wir in der Webredaktion haben so viele Kalender laufen, dass es super schnell sehr unübersichtlich wird.

Ich weiß nicht, ob andere Abteilungen sich diese Archiv-Funktion gewünscht haben, aber uns wäre es lieber, wenn abgelaufene Veranstaltungen automatisch gelöscht werden. Vielleicht könnte das auch eine optionale Einstellung sein? Die Admins können entscheiden, wie mit abgelaufenen Veranstaltungen umgegangen wird?

**Comment by cassandre** [comment]
Ich habe es jetzt so umgesetzt, dass man in den Einstellungen wählen kann, ab wie viele Tage in der Vergangenheit Veranstaltungen importiert werden sollen (min: 30, max. 365, default: 365). Ist im nächsten Update drin.
