### ISSUE TITLE
Falsche PHP-Version?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-calendar#17]
Ich versuche immer noch verzweifelt, auf meiner Instanz das Plugin zu aktivieren, scheitere aber daran, dass die PHP-Version wohl zu alt ist. Hilfe, was kann ich tun? :o)
![14-09-_2016_08-38-29](https://cloud.githubusercontent.com/assets/11296947/18502374/14a96a00-7a57-11e6-9f2d-3c55bff72ba0.png)

**Comment by rvdforst** [comment]
Die Ursache war eine veraltete Version des Plugins und es wurde bereits aktualisiert.
