### ISSUE TITLE
ICS-Export für Kategorie funktioniert nicht

### ISSUE THREAD

**Issue by TFWebm** [RRZE-Webteam/rrze-calendar#176]
Der Export-Link über den Shortcode-Parameter "abonnement_link" gibt diskrete Termine aus (https://www.tf.fau.de/?ical-plugin=rrze-calendar&action=export&ids=22907,22804,22964,22904,22804,22804,22965,22804,22966,22804), was für die Aktualität der Daten schlecht ist.

Der kontinuierliche Link über die Kategorie funktioniert nicht: https://www.tf.fau.de/?ical-plugin=rrze-calendar&action=export&cats=144

**Comment by rvdforst** [comment]
Der Fehler, der das Problem verursacht hat, wurde bereits behoben. Siehe https://github.com/RRZE-Webteam/rrze-calendar/commit/878c4af5d03f7da21e37c401557984da78c3a16b
