### ISSUE TITLE
Uhrzeit wird falsch ausgegeben

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-calendar#18]
Der Termin https://www.nat.fau.de/event/international-evening-fuer-studierende-der-naturwissenschaftlichen-fakultaet-8/? ist im Exchange-Kalender für den 28.11.16 mit 18 - 20 Uhr eingetragen. Auf der Webseite wird er aber mit 17 - 19 Uhr angezeigt.

**Comment by cibsell** [comment]
Das Problem ist auch bei allen anderen Terminen, da sogar mit 2 Stunden Unterschied, z. B. https://www.nat.fau.de/event/promotionsvortrag-einfluss-des-knochenmarksstromas-auf-den-metabolismus-der-akuten-myeloischen-leukaemie-5/? Der Termin findet von 10.-11.30 Uhr statt.

**Comment by cibsell** [comment]
Das Problem tritt auch bei anderen Webseiten auf, nicht nur auf der Fakultätsseite. Auch auf den Webseiten des Departments Chemie und Pharmazie und des Departments Biologie werden die Termine falsch ausgegeben. Auch der Feed eines nicht-Exchange-Kalenders wird falsch ausgegeben.

**Comment by xwolfde** [comment]
Ihr verwendet nicht das RRZE Calendar-Plugin, sondern FAU Events ( https://github.com/RRZE-Webteam/fau-events ). 
RRZE Calendar hat das Problem mit fehlerhaften Client-Einstellungen nicht. 

Wir sind dran, RRZE Calendar vorzeitig bereitzustellen, damit das Problem damit gelöst wird.
Da es Freitag bereits ein Telefongespräch gab, ist davon auszugehen, dass das Problem bekannt ist.

**Comment by csw-** [comment]
Danke für den Fix, das neue Plugin sieht im Backend auch richtig schön knorke aus. Und ich glaube der unschöne Fehler mit den unterschiedlichen Kachelabständen bei fehlender Orts- oder Zeitangabe ist jetzt auch behoben. Excellent.

**Comment by rvdforst** [comment]
Fehler behoben.
