### ISSUE TITLE
ICS Feeds - Google Kalendar

### ISSUE THREAD

**Issue by Jonas-Wo** [RRZE-Webteam/rrze-calendar#186]
Wir haben bei uns einen GoogleKalendar eingebunden. Leider hat das vor einiger Zeit aufgehört zu funktionieren. Das PlugIn erkennt zwar dass in dem Kalendar Events sind:
![grafik](https://github.com/RRZE-Webteam/rrze-calendar/assets/134267872/49628985-3900-4d33-a7af-ff1b6ab82246)
Aber läd diese nicht:
![grafik](https://github.com/RRZE-Webteam/rrze-calendar/assets/134267872/766e425b-717c-4ca2-bcd1-5567fdf715fe)
Ich habe es mit verschiedenen Versionen des PlugIn versucht und sämtlichen unterschiedlichen ICS Links die der GoogleKalendar anbietet. Andere Kalendar wie "ICS Kalendar" funktionieren mit dem Kalendar.  
Was könnte hier das Problem sein oder gehen GoogleKalendare mit dem PlugIn nicht mehr?

**Comment by rvdforst** [comment]
Version 2.1.1 verbesserte die Handhabung der Veranstaltungen im Zusammenhang mit nicht verknüpften oder unveröffentlichten ICS-Feeds. Aktualisieren Sie einfach das Plugin auf V. 2.1.1 und der Cronjob übernimmt die Wartung. Eine andere Alternative wäre, die Veranstaltungen, die dem betreffenden ICS-Feed entsprechen, manuell zu löschen.
