### ISSUE TITLE
Probleme mit gelöschten Serienterminen?

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-calendar#19]
Die Kollegen vom Career Service der Wiso haben ein kleines Problem mit ihrem Kalender: Und zwar haben sie in ihrem Outlook-Kalender einige viele Termine aus einer Serie gelöscht, diese sind aber weiterhin auf der Webseite aufgeführt.  (Der ics-Feed wurde bereits manuell aktualisiert - das Problem war auch schon mit "RRZE Termine" vorhanden)

Konkret haben sie etwa die Montags-Sprechstunden während der Semesterferien gelöscht. Wenn ich den Feed (http://groupware.fau.de/owa/calendar/wiwi-career-service@fau.de/Homepage_CareerService/calendar.ics) in Outlook öffne, wird mir das auch so korrekt angezeigt. 
Auf der Webseite werden diese Montags-Termine allerdings noch weiterhin angezeigt (https://www.career.rw.fau.de/event/?calendar=monat_2016-09-01)....

**Comment by rvdforst** [comment]
Fehler behoben.
