### ISSUE TITLE
Beim Aktualisieren von Feeds wurden Feed-Einträge dubliziert

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-calendar#20]
Ich wollte gerade die Termine der https://www.fbv.rw.fau.de/ auf das neue Plugin überführen und dabei ist folgendes passiert (Siehe Anhang):

Als die manuelle Feed-Aktualisierung abgeschlossen war, hat die Übersicht neu geladen und es wurde der Google-Feed zwei weitere Male ausgegeben - allerdings mit Terminanzahl: 0.
Beim Versuch diese zwei neuen zu löschen, hat er diese dann erneut um die Anzahl der vorhandenen Feeds verdoppelt ausgegeben. Ich nehme an die Reihe (16,32,..) würde dann so weitergeführt werden, aber das will ich jetzt nicht testen ;) 

![feeds-duplikate](https://cloud.githubusercontent.com/assets/6545158/18847211/9683b964-8429-11e6-9e88-66a380c4a85e.png)

**Comment by csw-** [comment]
Kurze Anmerkung: Jedesmal wenn ich die Feed-Übersicht aufrufe, werden vier weitere Feed-Einträge erstellt.

**Comment by rvdforst** [comment]
Fehler behoben.
