### ISSUE TITLE
Shortcodes aus FAU Events weiterhin gültig?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-calendar#21]
Ich teste gerade durch, ob die shortcodes aus FAU Events noch gültig sind; dabei habe ich Probleme mit page_link; auf der Zielseite wird nichts angezeigt. Bitte mal kurz prüfen, auch wenn ich nicht glaube, dass irgendjemand diesen Shortcode überhaupt nutzt.

**Comment by csw-** [comment]
*hust* :)

**Comment by csw-** [comment]
Also das page_link-Attribut funktioniert bei uns jedenfalls korrekt.

**Comment by AstridSemm** [comment]
Dann liegt's an mir, vermute ich. Gehe ich morgen nochmal bei. :o)
