### ISSUE TITLE
page_link / Linktext wird nicht übersetzt

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/rrze-calendar#23]
Beim Einsatz des page_link-Attributes auf einem englischssprachigen Webauftritt wird weiterhin der deutsche Text "Mehr Veranstaltungen" ausgegeben.

![pagelink](https://cloud.githubusercontent.com/assets/6545158/19014864/7ef3fb24-87f8-11e6-9d0e-f996d555ffb8.png)

**Comment by rvdforst** [comment]
Fehler behoben.
