### ISSUE TITLE
Jahresangabe zugreifbar machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#25]
Wir brauchen eine Funktion wie get_year_date() um das Jaghr zu erhalten.

Dies wird benötigt um optional das Jahr sichtbar mit auszugeben.
vgl https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/178

Ausserdem muss das jahr unsichtbar mit ausgebbar sein um Schema-org Markup zu liefern

**Comment by rvdforst** [comment]
Neue Eigenschaft RRZE_Calendar_Event::start_year (Gibt ein vierstelliges Jahr aus des Startdatums).
Benutzung im FAU-Themes: $event->start_year
