### ISSUE TITLE
Kalenderfarbe stimmt bei einigen Kategorien nicht

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/rrze-calendar#26]
...ich weiß nicht, wo ich etwas falsch eingestellt haben könnte. Wir haben Feedeinträge nach Kategorien und Schlagwort, die Farben zugeordnet sind:

![kal-kat](https://cloud.githubusercontent.com/assets/9445370/20219439/b63da796-a829-11e6-9957-7a2911057c34.JPG)

Binde ich diese Termine nun nach Schlagworten ein, dann ist die Farbe bei manchen Kategorien wie gewünscht, bei anderen einfach FAU-blau.

Hier funktioniert es nicht:

- https://www.fau.de/veranstaltungen-des-fachbereichs-wirtschaftswissenschaften/
- https://www.fau.de/veranstaltungen-der-technischen-fakultaet/
- https://www.fau.de/veranstaltungen-des-fachbereich-rechtswissenschaften-der-rechts-und-wirtschaftswissenschaftlichen-fakultaet/

Hier funktioniert es und so haben wir es (wie oben auch) gemacht:

Auf der Seite der Natfak https://www.fau.de/veranstaltungen-der-naturwissenschaftlichen-fakultaet/
habe ich folgenden Shortcode benutzt: [termine schlagworte="natfak-ausfuehrlich"  anzahl="100" abonnement_link="0"]

Das Schlagwort wurde nur für Feeds verwendet, die als Kategorie "Naturwissenschaftliche Fakultät" erhielten - und diese Kategorie ist mit der Farbe grün verknüpft (siehe oben).

Medfak geht auch: https://www.fau.de/veranstaltungen-der-medizinischen-fakultaet/

Zu guter Letzt noch die Feedübersicht, da stimmen die Kategoriezuordnungen sichtbar:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/20219584/707d528c-a82a-11e6-97ba-3d04133db2b6.jpg)

Wo liegt der Fehler?

**Comment by wrkb** [comment]
@rvdforst @xwolfde

**Comment by wrkb** [comment]
Ich bin geneigt, Bedienfehler unsererseits mit großer Wahrscheinlichkeit auszuschließen. Auch auf der Startseite von fau.de stimmen die Farben nicht mehr. Beispiel: https://www.fau.de/termine/gastvortrag-die-arbeit-des-himmels-dov-the-scribe/ ist im Exchange-Kalender der Philfak eingestellt (wir haben für jede Fakultäten einen eigenen im Outlook) und im CMS mit der richtigen Farbe verknüpft - und das schon seit Langem - hier wurde nichts geändert durch uns.

Es ist also momentan so, dass alle Fachbereiche/Fakultäten außer Med und Nat in blau angezeigt werden, anstatt in der eigenen Farbe.

Wir halten derzeit die Publikation der neuen Seiten zurück, ein Feedback zum Problem wäre schön.

Danke und Grüße

@rvdforst @xwolfde

**Comment by rvdforst** [comment]
Das Problem liegt im Theme (FAU-Einrichtungen). Die Kalender-Templates haben ein Bug. Wir werden so bald wie möglich den Fehler beheben.
