### ISSUE TITLE
Doppelte Termine 

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-calendar#27]
Ich speise in den Kalender der Nat. Fakultät mehrere Feeds von verschiedenen Kalendern ein. Ab und an habe ich dann das Problem, dass der gleiche Termin, der in zwei unterschiedlichen Feeds steht, dann doppelt in meinem Kalender auftaucht. Technisch gesehen macht das Plugin ja alles richtig, aber es ist natürlich nicht sinnvoll, dass der Termin zweimal in meinem Kalender auftaucht. Gibt es eine Möglichkeit den doppelten Eintrag händisch zu entfernen und ohne, dass er mit einer Aktualisierung wieder erscheint?

So zum Beispiel beim Eintrag zum Vortrag auf AEG von Prof. Büttner am 21.11.16: https://www.nat.fau.de/calendar/?calendar=tag_2016-11-21

**Comment by xwolfde** [comment]
Klar geht das: Der Mensch, der den Termin in beiden Kalendern einträgt, nochmal schulen, dass es falsch ist denselben Termin in zwei unterschiedlichen Kalendern einzutragen, welche später wieder gemergt werden.

Oder halt nur den einen Kalender importieren, aber nicht den anderen.

Worauf die vielleicht hinwillst: Ob wir es automatisch erkennen könnten, dass Dupletten aus unterschiedlichen Importen kommen und die erkannten Dupletten dann rauswerfen.
Wäre vielleicht denkbar...

Nur würde das Problem dann für andere Anwender, die direkt die Feeds auslesen in eigenen Clients oder im Outlook (und nicht über Web) trotzdem bestehen bleiben.Daher wäre es sinnvoller, das Problem organisatorisch zu lösen und nicht technisch.

Was nutzt es, wenn wir hier eine Duplettenerkennung bauen, dafür Zeit investieren und die Anwender werden das Problem aufgrund der weiterhin bestehenden Probleme bei der ANzeige im Outlook dann doch irgendwann lösen. Dann haben wir umsonst Zeit verbraten.

**Comment by cibsell** [comment]
Da sitzen aber unterschiedliche Menschen dahinter, die primär natürlich ihre eigenen Webseiten / Kalender im Blick haben und nicht wissen, dass ihre eingetragenen Termine eventuell von anderen Personen in deren Kalendern auch eingetragen werden (z. B. wenn es eine gemeinsame Veranstaltung ist) und diese Kalender dann gemeinsam als Feed auf einer dritten Webseite auftauchen. 

Anderer Fall:
Zum Beispiel habe ich auch den Fall gehabt, dass sich ein Mitarbeiter die Mühe gemacht hat in seinen Schülerkalender die Vortragstermine bei den FAU-Infotagen zu seinen Studiengängen eingetragen hat. Allerdings werden bei den FAU-Infotagen noch mehr Vorträge zu unterschiedlichen Studiengängen gehalten. In der Regel sind das für die NAT ca. 10-15 Vorträge an einem Tag. Für die anderen Vorträge gibt es jedoch aus anderen Feeds keine Einträge, so dass ich in den NAT-Kalender einen einzigen Termin für alle Vorträge machen würde. Da der Schülerkalender des Mitarbeiters jedoch auch als Feed eingelesen wird, tauchen die FAU-Infotage dann trotzdem 2x auf der NAT-Webseite auf. Da wäre es durchaus praktisch, wenn ich den Termin mit dem einzelnen Vortrag händisch rauslöschen könnte. 

Wie soll ich denn in so einem Fall idealerweise vorgehen? Der Mitarbeiter wird seinen Termin nicht löschen, weil dieser auf seiner Webseite eingelesen wird und er nicht alle anderen Schülerveranstaltungen der NAT importieren will. Er wird auch kein Interesse daran haben seinen Termin so zu ändern, dass alle Vorträge in seinem Termin auftauchen, da es sich im schlimmsten Fall um "Konkurrenzveranstaltungen" handelt bzw. von "weiter oben" als unnötige zusätzliche Information angesehen wird.

Es ist mir klar, dass das alles Einzelfälle sind. Vermutlich macht die NAT auch einfach nur wieder mal alles falsch. ;-) Ich kann auch damit leben, dass Einträge doppelt auftauchen, es schaut halt einfach nicht schön aus.

> Nur würde das Problem dann für andere Anwender, die direkt die Feeds auslesen in eigenen Clients oder im Outlook (und nicht über Web) trotzdem bestehen bleiben.Daher wäre es sinnvoller, das Problem organisatorisch zu lösen und nicht technisch.

Mit Outlook habe ich das Problem nicht, weil ich da beliebig Termine aus abonnierten Feeds rauslöschen kann.

**Comment by xwolfde** [comment]
Nicht missverstehen. Ich sehe die Anfrage durchaus als berechtigt und sinnvoll an.
 Es geht mir nur darum, dass wir halt mit unser beschränkten und weiter reduzierten Wo/Manpower errstmal andere Workarounds suchen sollten... Alles nur ne Zeitfrage.
