### ISSUE TITLE
Anzeige Termine Sidebar Startseite

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-calendar#37]
Hallo zusammen, habe folgende Sache vorhin auch schon mit Astrid besprochen und es gibt auch schon ein Ticket (#2017070342001621):
Bei der Ausgabe von Terminen durch [termine anzahl="7"] wird bei Terminen, die über einen längeren Zeitraum andauern, jeweils jeder Tag als jeweils ein Termin gezählt. So kann sich u.U. täglich die Anzahl von ausgegebenen Terminen ändern, gerade wenn mehrere über einen längeren Zeitraum gehen. Im konkreten Fall gehörten z.B. der erste und letzte Termin zu einer "Reihe" und es wurden 4 Termine anstatt 7 ausgegeben. Das sieht auf der Startseite dann zum Teil nicht sehr schick aus. Hier wäre es super, wenn jeweils der komplette Zeitraum als ein Termin gezählt werden würde.

**Comment by ec89yler** [comment]
Hallo zusammen, wollte nachfragen, ob es hier schon ein Update gibt? Hatten im Moment anstatt der 7 abgefragten Termine nur noch 3 auf der Startseite. Habe die Anzahl nun erhöht, ist aber ein eher umständlicher Workaround, da man das dann eigentlich täglich kontrollieren muss.. Danke euch und viele Grüße Marcus

**Comment by rvdforst** [comment]
Ich glaube, dass der Fehler ist schon behoben.
