### ISSUE TITLE
Darstellungsfehler Kalender auf der Startseite

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-calendar#38]
Wenn man auf der Startseite einen Übersichtskalender einbindet, ergeben sich zwei interessante Effekte:
1.) Der in der Sidebar eingebundene Kalender wird sehr merkwürdig dargestellt.
![bildschirmfoto 2017-11-29 um 16 50 58](https://user-images.githubusercontent.com/11296947/33384160-88e159c6-d525-11e7-84a8-76f9cee07fd8.png)
(Gut, das will jetzt eigentlich auch niemand, aber es ist halt trotzdem da, deswegen der Vollständigkeit halber)
2.) Beim Klick auf die Pfeile links und rechts von "Heute" wird eine Artikelübersicht angezeigt; heißt, unter dem Link https://www.alfirin.test.rrze.uni-erlangen.de/?calendar=monat_2017-12-01 wird nicht der Monat Dezember des Übersichtskalenders ausgegeben, sondern eine Übersicht über die Artikel aus der blogroll.
Letzteres ist deutlich unschöner als das erste. Der Fehler bleibt auch bestehen, wenn man den Kalender aus der Sidebar löscht.

**Comment by rvdforst** [comment]
Vgl. https://github.com/RRZE-Webteam/rrze-calendar/issues/81
