### ISSUE TITLE
Kalenderprobleme

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-calendar#39]
Es häufen sich die Anfragen zum Kalender, weil bei bestehenden Kalendern das Update nicht mehr funktioniert.

Ich habe heute morgen einer Schülerin gezeigt, wie man einen Feed einbindet, die Termine werden aber auch bei Aktualisierung von Hand nicht angezeigt. Bitte dringend prüfen!

**Comment by cibsell** [comment]
Hat sich da schon etwas getan? Bei mir fliegen immer wieder Einträge raus oder die Feeds werden nicht mehr aktualisiert, so dass ich die Feeds händisch anschubsen muss. Das ist ein wenig nervig und es häufen sich Beschwerden, wieso die Einträge nicht angezeigt werden.

**Comment by rvdforst** [comment]
Der Fehler wurde bereits behoben.
