### ISSUE TITLE
Fatal Error bei Aktivierung des Plugins

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#4]
Bei Aktivierung des Plugins (egal ob FAU Events aktiv ist oder nicht) erhalte ich eine weiße Seite/Fatal Error.
Danach bliebt das Plugin trotzdem aktiv, die Seite ist fortan  unzugänglich. Das Plugin muss manuell durch wegschieben des verzeichnisses im Plugin-Ordner deaktiviert werden.

In der Errorlog steht bei der Aktivierung:

`[Wed Aug 17 16:02:55.486324 2016] [:error] [pid 15483] [client 131.188.78.36:58474] WordPress-Datenbank-Fehler Specified key was too long; max key length is 767 bytes f\xc3\xbcr Abfrage CREATE TABLE wp_9_rrze_calendar_feeds (\n            id bigint(20) unsigned NOT NULL auto_increment,\n            url varchar(255)  NOT NULL default '',\n            title varchar(255)  NOT NULL default '',\n            active tinyint(1) NOT NULL default '0',\n            created datetime NOT NULL default '0000-00-00 00:00:00',\n            modified datetime NOT NULL default '0000-00-00 00:00:00',\n            PRIMARY KEY (id),\n            UNIQUE KEY url (url)\n            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci von require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, RRZE_Calendar::instance, RRZE_Calendar->__construct, RRZE_Calendar::update_version, RRZE_Calendar::db_delta, dbDelta, referer: http://test8.tindu.rrze.uni-erlangen.de/wp-admin/plugins.php
[Wed Aug 17 16:02:55.499754 2016] [:error] [pid 15483] [client 131.188.78.36:58474] PHP Fatal error:  Arrays are not allowed in class constants in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-calendar/includes/calendar-functions.php on line 126, referer: http://test8.tindu.rrze.uni-erlangen.de/wp-admin/plugins.php

`

**Comment by rvdforst** [comment]
Ah! Mein Fehler! InnoDB + CHARACTER SET utf8mb4 = 767 bytes / 4 bytes = 191 chars! (InnoDB-Begrenzung). Lösung: Ich muß die Größe der Indizes anpassen.

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Siehe #6
