### ISSUE TITLE
Kalender zeigt mehrtägigen, ganztägigen Termin am zweiten Tag nicht mehr an

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-calendar#42]
Im Kalenderplugin wird der folgende Termin (Screenshot aus OWA-Kalender)
![image](https://user-images.githubusercontent.com/11389126/39618325-85945100-4f83-11e8-844e-b493775086da.png)
am 04.05.2018 nicht mehr angezeigt. Eigentlich sollte er mindestens bis 04.05.2018 23:59 Uhr angezeigt werden.
![image](https://user-images.githubusercontent.com/11389126/39618376-ba56e894-4f83-11e8-8a9e-c8eb4c01e2ad.png)

**Comment by ej64ojyw** [comment]
Ergänzend zum obigen Issue aus Helpdesk (http://go.fau.de/9ra2i #1 Punkt 1):

Wenn wir ganztägige Termine eintragen, die über einen längeren Zeitraum gehen, wird auf der Homepage immer der Endtag +1 angezeigt, der Termin wird also einen Tag länger benannt.

Des Weiteren verschwinden Termine, die über einen längeren Zeitpunkt gehen, bereits wieder ab dem Beginn der Veranstaltung und bleiben nicht die ganze Dauer bestehen.

**Comment by xwolfde** [comment]
Wir müssen da mal bei Exchange reinschauen, wie das ICS in den jeweiligen Fällen ausschaut:
- Termin mit Startzeit DATUM, Endzeit DATUM (+1 Tag)
- Termin mit Startzeit DATUM, Endzeit DATUM (+1 Tag), Haken bei Ganztägiger Termin
- Termin mit Startzeit DATUM, Endzeit DATUM 
- Termin mit Startzeit DATUM, Endzeit DATUM, Haken bei Ganztägiger Termin
- Termin mit Startzeit DATUM, keine Endzeit eingegeben
- Termin mit Startzeit DATUM,keine Endzeit eingegeben, Haken bei Ganztägiger Termin

**Comment by xwolfde** [comment]
Gecancelt wegen Umstieg auf neuem Plugin
