### ISSUE TITLE
Kalendereinträge mit Kategorie/Titel des Kalenders versehen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-calendar#43]
Bei einzelnen Terminen - ähnlich wie beim Blog - Kategorie oder Titel des Feeds mit anzeigen, um Termine ohne genaue Angaben leichter zuordnen zu können… :-) Ähnliches hatten wir kürzlich auf fau.eu auch schon.

**Comment by xwolfde** [comment]
Shortcode erweitern um show/hide-Parameter

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
