### ISSUE TITLE
Test auf FAU EVENTS?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#5]
Arbeitet das Plugin eigentlich mit FAU Events zusammen bzw parallel?

Wenn FAU Events aktiv ist und man  das Plugin RRZE Calendar aktivieren will, sollte da  nicht eine Warnung oder ein Hinweis kommen? Sollte das überhaupt gehen?

**Comment by rvdforst** [comment]
Beide Plugins sind unabhängig und können gleichzeitig aktiviert werden.
