### ISSUE TITLE
No proper English translation

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/rrze-calendar#50]
Leider klappt die Nutzung des Plugins mit English als WordPress-Sprache nicht: 
![bildschirmfoto 2018-11-17 um 15 06 14](https://user-images.githubusercontent.com/1886360/48661941-5a7f4500-ea7a-11e8-8292-48e398ebfcee.png)

[Link](https://osr.cs.fau.de)

Wie wäre es mit `14:00 - 16:00`?

**Comment by rvdforst** [comment]
Der Fehler wurde bereits behoben.
