### ISSUE TITLE
Falsche Uhrzeit im widget

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/rrze-calendar#52]
Die über `[termine]` als Widgets angezeigten Events werden als 1h zu früh angezeigt. Klickt man auf ein Event kommt zu dem Kalendereintrag auf dem Blog (z.B. auf der Startseite von https://osr.cs.fau.de), und auch hier stimmt die Uhrzeit (ist also eine andere als jene, die noch auf der Homepage angezeigt wird. Fehler im widget?

![bildschirmfoto 2018-12-19 um 11 53 19](https://user-images.githubusercontent.com/1886360/50215953-c825d600-0384-11e9-8abe-9a67c7795326.png)
-----
![bildschirmfoto 2018-12-19 um 11 53 29](https://user-images.githubusercontent.com/1886360/50215952-c78d3f80-0384-11e9-8648-a9a28d8acfcd.png)

**Comment by rvdforst** [comment]
Der Fehler wurde bereits behoben.
