### ISSUE TITLE
Einzelnen Termin anzeigen lassen

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-calendar#53]
Wie kann man einen einzelnen Termin anzeigen lassen?

Wir haben einen gemeinsamen Kalender, in dem alle Vorträge am Department eingetragen werden. Der SFB möchte auf seiner Unterseite nur die SFB-Termine anzeigen lassen.

**Comment by endv02** [comment]
Das ist leider technisch nicht möglich. In diesem Fall sollte das SFB überlegen, einen eigenen Exchange-Kalender zu pflegen, der dann zusätzlich beim Department mit angezeigt wird.
