### ISSUE TITLE
Gleichnamige Veranstaltungen zu unterschiedlichen Terminen mit ARIA-Title unterscheidbar machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-calendar#60]
Um den Fehler
"Link-Text wird für mehrere unterschiedliche Ziele verwendet"
zu vermeiden, sollte mit Hilfe von ARIA der jeweilige Link der zu unterschiedlichen ZIelen geht, entsprechend deklariert werden.
![grafik](https://user-images.githubusercontent.com/1070669/66389111-1f01a800-e9b7-11e9-8aee-0c594f746e02.png)

**Comment by xwolfde** [comment]
(Ok, in diesem Fall IST es derselbe Termin und es war nur ein redundazter Eintrag, aber es gibt trotzdem regelmäßige Termine; Dort ist das dann zu tun)

**Comment by AndiWebred** [comment]
Ich habe das Problem auch gerade. Ein Beispiel wäre hier: https://www.fau.de/veranstaltungen/veranstaltungen-des-fau-rechenzentrums-rrze/

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
