### ISSUE TITLE
Keine Links zu Terminen am endpoint .../events

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-calendar#62]
Uns ist aufgefallen, dass am endpoint .../events zwar die Termine angezeigt, jedoch nicht verlinkt werden. Die Links bei den Terminen zeigen alle auf den endpoint .../events statt auf .../events/terminx. 

![image](https://user-images.githubusercontent.com/11389126/67844301-d17fe300-fafd-11e9-9027-d981fff9a24e.png)

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Vgl. https://github.com/RRZE-Webteam/rrze-calendar/commit/e8169be27d1b41191b0576cfba2ff84d8737c6a7
