### ISSUE TITLE
Kein HTML bei Terminen mehr?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-calendar#63]
Bei uns im Sekretariat ist aufgefallen, dass neuerdings (oder schon länger) bei Outlook-Terminen keine HTML-Formatierungen mehr übernommen werden. Es ist unabhängig davon, ob man den Termin als "HTML" oder "Nur Text" formatiert - spätestens bei der Anzeige des Termins via Kalender-Plugin gehen alle Formatierungen, inline-Styles und sonstige HTML-Strukturen verloren. Links werden nun scheinbar automatisch aus URLS erzeugt; auch das Einbinden von Bildern aus der wp-Mediathek in die Termine funktioniert nicht mehr wie gehabt, da alle HTML-Tags ignoriert werden.

Das heißt, alle in mühsamer Sekretärinnen- und Hiwi-Arbeit liebevoll strukturierten Termine sehen jetzt so aus:
![image](https://user-images.githubusercontent.com/11389126/67846085-e4e07d80-fb00-11e9-8c0d-f55c3639de7d.png)

Das sorgt akut für Unmut und wir fragen uns, 

- ob die "neue" HTML-freie Terminausgabe Plugin-seitig bewusst so vorgesehen ist, und wenn ja, ob dies auch irgendwie kommuniziert wurde (haben wir was verpasst?)
- oder ob das an Outlook/Exchange liegt (weil selbst damit erzeugtes HTML nach dem Speichern in der Terminanzeige _in Outlook_ verloren geht)
- ob wir unsere Termine jetzt alle "bereinigen" bzw. umbauen müssen
- oder ob es vielleicht im Plugin möglich wäre, eine Option zu integrieren, um die HTML-Ausgabe in Terminen ein- oder auszuschalten?
- oder machen wir einfach irgendwas falsch?

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Vgl. https://github.com/RRZE-Webteam/rrze-calendar/commit/46530e7a304d04128ac4fcd482a5efd7a3ab167c
