### ISSUE TITLE
Kalender: Update der Einträge

### ISSUE THREAD

**Issue by mklotz29** [RRZE-Webteam/rrze-calendar#7]
Wenn ich https://anglistik.cms.rrze.uni-erlangen.de aufrufe, bekomme ich auf dem auf der Startseite eingebetteten Kalender oft nicht alle (bzw. gelegentlich auch gar keine) Einträge zu sehen. Wenn ich einen Refresh (F5) der Seite mache, erscheinen alle Einträge.

**Comment by AstridSemm** [comment]
Das liegt am Browsercache; Ihr Browser speichert lokal die letzte Version der Seite ab, die Sie aufgerufen haben, gleicht aber bei einem erneuten Aufruf nicht ab, ob sich etwas an der Seite geändert hat. Deswegen wird es mit einem Refresh auch angezeigt. Lösung: Im Browser nachsehen, wie die Cache-Einstellungen sind und diese eventuell ändern.

**Comment by mklotz29** [comment]
Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.

**Comment by steffigebel** [comment]
Welchen Browser nutzen Sie denn? Haben Sie ähnliche Phänomene in anderen Browsern auch?

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: mklotz29 <notifications@github.com>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com>
Datum: Donnerstag, 18. August 2016 um 14:40
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)


Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.

**Comment by mklotz29** [comment]
Hallo Frau Gebel,

ich benutzte Opera 39.0. Habe gerade mal nachgesehen. Die Option, den Cache zu deaktivieren, schein da gar nicht mehr vorgesehen zu sein ☹. Gibt es von Serverseite/Wordpress aus eine Möglichkeit, das Caching abzuschalten und den Browser zu zwingen, die Daten immer neu zu holen? Das wäre auf Seiten, auf denen sich die Informationen öfters ändern, vielleicht sinnvoll.

Beste Grüße,
mk
___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1   91054 Erlangen
09131 8522938
Michael.klotz@fau.de

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 14:54
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: Klotz, Michael <michael.klotz@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Welchen Browser nutzen Sie denn? Haben Sie ähnliche Phänomene in anderen Browsern auch?

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>
www.rrze.fau.de<http://www.rrze.fau.de>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 18. August 2016 um 14:40
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)


Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.

**Comment by steffigebel** [comment]
Lieber Herr Klotz,

vielleicht hilft das: http://help.opera.com/Windows/12.10/de/cache.html
Browsereinstellungen sind immer individuell, da können wir Serverseitig nichts machen. WP-seitig aktualisieren sich die Termine je nach Einstellung in den „Termine“-Optionen im Backend von WP.
So lange nur Sie das Problem haben, wäre es ja kein Thema ☺ Hauptsache Ihre Zielgruppe sieht immer alles ☺ Fragen Sie doch mal bei anderen nach.

Grüße,
Steffi Gebel

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: mklotz29 <notifications@github.com>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com>
Datum: Donnerstag, 18. August 2016 um 14:59
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de>, Comment <comment@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Hallo Frau Gebel,

ich benutzte Opera 39.0. Habe gerade mal nachgesehen. Die Option, den Cache zu deaktivieren, schein da gar nicht mehr vorgesehen zu sein ☹. Gibt es von Serverseite/Wordpress aus eine Möglichkeit, das Caching abzuschalten und den Browser zu zwingen, die Daten immer neu zu holen? Das wäre auf Seiten, auf denen sich die Informationen öfters ändern, vielleicht sinnvoll.

Beste Grüße,
mk
___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1 91054 Erlangen
09131 8522938
Michael.klotz@fau.de

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 14:54
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: Klotz, Michael <michael.klotz@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Welchen Browser nutzen Sie denn? Haben Sie ähnliche Phänomene in anderen Browsern auch?

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>
www.rrze.fau.de<http://www.rrze.fau.de>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 18. August 2016 um 14:40
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)


Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.

**Comment by mklotz29** [comment]
Opera 12 war noch eine Eigenentwicklung und bot viele Einstellmöglichkeiten. Inzwischen basiert Opera auf Chrome und bietet kaum noch Konfiguration. Wäre ja, wie Sie sagen, nicht schlimm, wenn es nur mich betrifft. Ich weiß ja, was auf der Seite zu stehen hat ☺. Ich werde aber mal die Kollegen in der Web-Gruppe am Institut bitten, das mit zu beobachten.

Danke und beste Grüße,
mk


___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1   91054 Erlangen
09131 8522938
Michael.klotz@fau.de<mailto:Michael.klotz@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 15:04
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: Klotz, Michael <michael.klotz@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Lieber Herr Klotz,

vielleicht hilft das: http://help.opera.com/Windows/12.10/de/cache.html
Browsereinstellungen sind immer individuell, da können wir Serverseitig nichts machen. WP-seitig aktualisieren sich die Termine je nach Einstellung in den „Termine“-Optionen im Backend von WP.
So lange nur Sie das Problem haben, wäre es ja kein Thema ☺ Hauptsache Ihre Zielgruppe sieht immer alles ☺ Fragen Sie doch mal bei anderen nach.

Grüße,
Steffi Gebel

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>
www.rrze.fau.de<http://www.rrze.fau.de>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 18. August 2016 um 14:59
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>, Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Hallo Frau Gebel,

ich benutzte Opera 39.0. Habe gerade mal nachgesehen. Die Option, den Cache zu deaktivieren, schein da gar nicht mehr vorgesehen zu sein ☹. Gibt es von Serverseite/Wordpress aus eine Möglichkeit, das Caching abzuschalten und den Browser zu zwingen, die Daten immer neu zu holen? Das wäre auf Seiten, auf denen sich die Informationen öfters ändern, vielleicht sinnvoll.

Beste Grüße,
mk
___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1 91054 Erlangen
09131 8522938
Michael.klotz@fau.de<mailto:Michael.klotz@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 14:54
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Cc: Klotz, Michael <michael.klotz@fau.de<mailto:michael.klotz@fau.de>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Welchen Browser nutzen Sie denn? Haben Sie ähnliche Phänomene in anderen Browsern auch?

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>>
www.rrze.fau.de<http://www.rrze.fau.de<http://www.rrze.fau.de%3chttp:/www.rrze.fau.de>>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 18. August 2016 um 14:40
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com%3cmailto:rrze-calendar@noreply.github.com>>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)


Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.

**Comment by steffigebel** [comment]
Auch eine Idee ☺

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: mklotz29 <notifications@github.com>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com>
Datum: Donnerstag, 18. August 2016 um 15:10
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de>, Comment <comment@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Opera 12 war noch eine Eigenentwicklung und bot viele Einstellmöglichkeiten. Inzwischen basiert Opera auf Chrome und bietet kaum noch Konfiguration. Wäre ja, wie Sie sagen, nicht schlimm, wenn es nur mich betrifft. Ich weiß ja, was auf der Seite zu stehen hat ☺. Ich werde aber mal die Kollegen in der Web-Gruppe am Institut bitten, das mit zu beobachten.

Danke und beste Grüße,
mk


___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1 91054 Erlangen
09131 8522938
Michael.klotz@fau.de<mailto:Michael.klotz@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 15:04
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com>
Cc: Klotz, Michael <michael.klotz@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Lieber Herr Klotz,

vielleicht hilft das: http://help.opera.com/Windows/12.10/de/cache.html
Browsereinstellungen sind immer individuell, da können wir Serverseitig nichts machen. WP-seitig aktualisieren sich die Termine je nach Einstellung in den „Termine“-Optionen im Backend von WP.
So lange nur Sie das Problem haben, wäre es ja kein Thema ☺ Hauptsache Ihre Zielgruppe sieht immer alles ☺ Fragen Sie doch mal bei anderen nach.

Grüße,
Steffi Gebel

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>
www.rrze.fau.de<http://www.rrze.fau.de>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 18. August 2016 um 14:59
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>, Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Hallo Frau Gebel,

ich benutzte Opera 39.0. Habe gerade mal nachgesehen. Die Option, den Cache zu deaktivieren, schein da gar nicht mehr vorgesehen zu sein ☹. Gibt es von Serverseite/Wordpress aus eine Möglichkeit, das Caching abzuschalten und den Browser zu zwingen, die Daten immer neu zu holen? Das wäre auf Seiten, auf denen sich die Informationen öfters ändern, vielleicht sinnvoll.

Beste Grüße,
mk
___
Dr. Michael Klotz
Lehrstuhl Anglistik: Linguistik
Friedrich-Alexander-Universität Erlangen-Nürnberg
Bismarckstr. 1 91054 Erlangen
09131 8522938
Michael.klotz@fau.de<mailto:Michael.klotz@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. August 2016 14:54
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com>>
Cc: Klotz, Michael <michael.klotz@fau.de<mailto:michael.klotz@fau.de>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)

Welchen Browser nutzen Sie denn? Haben Sie ähnliche Phänomene in anderen Browsern auch?

--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>>
www.rrze.fau.de<http://www.rrze.fau.de<http://www.rrze.fau.de%3chttp:/www.rrze.fau.de>>

Von: mklotz29 <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/rrze-calendar <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 18. August 2016 um 14:40
An: RRZE-Webteam/rrze-calendar <rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com<mailto:rrze-calendar@noreply.github.com%3cmailto:rrze-calendar@noreply.github.com>>>
Betreff: Re: [RRZE-Webteam/rrze-calendar] Kalender: Update der Einträge (#7)


Das war auch mein erster Gedanke. Allerdings handelt es sich um Termine, die ich schon vor längerer Zeit angelegt hatte. Inzwischen habe ich die Website schon etliche Male besucht, so dass die Termine mit gecached sein müssten. Ich beobachte das mal weiter.
