### ISSUE TITLE
Dopplungen bei Serienterminen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-calendar#75]
In Outlook wird ein Serientermin zum Beispiel mit fünf Terminen erstellt. Danach wird jeder einzelne Termin nochmal angepasst, zum Beispiel der Ort oder der Titel (Bei Veranstaltungsreihen). Im Kalender auf der Webseite werden diese Termine dann doppelt angezeigt. Einmal der Serientermin und einmal die korrigierte Version - obwohl im Outlook-Kalender nur noch ein Termin steht.

**Comment by xwolfde** [comment]
Klingt für mich nach einem Sync-Problem von Exchange/ der Datenquelle.
Wir lesen ja nur das ICS aus., wie es erzeugt wird. Wenn das ICS noch falsche Einträge enthält und nicht aktualisiert wurde, können wir nichts tun.
Ebenso wenig, wenn der Termin noch im WP noch gecacht ist, aber im Exchange eine Ändeurng vorgenommen wurde.

Im Prinzip sollte sich dieses Problem von selbst lösen, nachdem die Quell-ICS aktualisiert wurde und der Cache im WP abgelaufen ist (>= 1 Stunde). Alternativ muss man im Backend von Hand die Termine neu aktualisieren.
