### ISSUE TITLE
Blättern funktioniert auf Startseite nicht

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-calendar#81]
Wenn der Kalender auf der Startseite eingebunden ist, funktioniert das Blättern zwischen den Monaten nicht. Man landet dann auf der Blog-Seite.
Vgl. https://www.existency.de -> https://www.existency.de/?calendar=monat_2021-03-01

**Comment by rvdforst** [comment]
Der Fehler wurde behoben. Die Query-Abfrage des Kalenders musste jedoch angepasst werden. Bspw. wurde die URL https://www.existency.de/?calendar=monat_2021-03-01 in die folgende URL geändert: https://www.existency.de/?rrze-calendar=2021-03-01
In der nächsten Version des Plugins (2.0) wird der Kalender automatisch mit JS generiert. Infolgedessen treten diese Probleme nicht mehr auf.
