### ISSUE TITLE
Warning in Template events.php

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-calendar#82]
`Warning: Invalid argument supplied for foreach() in [...]/plugins/rrze-calendar/includes/templates/themes/fau-events/events.php on line 28`.

`$event->tags` ist false, daher liefert `isset($event->tags)` ein `true`.
Der Fehler dürfte auch in den anderen Event-Template der gleiche sein.

**Comment by rvdforst** [comment]
Fehler wurde behoben.
