### ISSUE TITLE
Nach Feederstellung kann die Kategorie unter Feeds > bearbeiten nicht mehr geändert werden.

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-calendar#87]
Nach Feederstellung kann die Kategorie unter Feeds > bearbeiten nicht mehr geändert werden.

(Browser: Safari 15.1)

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
