### ISSUE TITLE
Event-Übersicht zeigt 404, wenn keine Termine vorhanden

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/rrze-calendar#89]
Die URL (im Backend unter "Endpoint-Titelform") zur Terminübersicht liefert einen 404-Fehler, wenn keine Termine in der Zukunft vorhanden sind. Besser wäre eine Meldung "Keine aktuellen Termine gefunden".

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.

**Comment by cassandre** [comment]
In der neuen Version nicht mehr zutreffend.
