### ISSUE TITLE
Schriftfarbe ändern oder Schriftfarbe automatisch anpassen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-calendar#94]
Auf fau.de nutzen wir unterschiedliche Kalender mit den jeweiligen Fakultätsfarben. Bei uns ist aber die Schriftfarbe immer weiß, ich kann damit die vitalen Farbe einiger Fakultäten, zb der Philfak nicht nutzen.

Unser Workaround ist gerade, dass wir die dunkleren Farben nutzen, aber die vitaleren Farben wären schöner.

Wäre es also möglich, auch die Schriftfarbe pro Kalender anzupassen?
Alternative: #41 Damit hätte man nur einen beschränkten Farbbereich zur Auswahl, die Schriftfarbe würde sich automatisch generieren.

**Comment by xwolfde** [comment]
Es ist ausdrücklich vom CD nicht gewollt, dass die CD Farbe als Schriftfarbe verwendet wird. Sie soll nur als Flächenfarbe verwendet werden.
Und auf dieser darf nur weiß oder schwarz als Schriftfarbe verwendet werden, um die Kontraste zu halten.
Abhängig von der gewählten CD Farbe wird die Schriftfarbe gewählt. Bei Phil ist es schwarz.

Als Schriftfarbe (auf Weiß) müsste die CD Farbe ja dann nämlich die Kontraste einhalten. Dies erfüllen die Farben der Agentur leider nicht.

**Comment by AndiWebred** [comment]
ah, das ist von mir wohl falsch formuliert gewesen. die schriftfarbe soll schwarz oder weiß bleiben!

aber auf fau.de passt sich die schriftfarbe eben nicht der kalenderblattfarbe an. da ist sie immer weiß, deswegen können wir für die kalenderblätter teilweise nicht die vitalen farben nutzen. deswegen: die beiden ideen. entweder ich kann bestimmen welche farbe die schrift hat (weiß oder schwarz) oder es geht automatisch und die auswahl für das kalenderblatt ist beschränkt.

**Comment by xwolfde** [comment]
Wählst du die Farben unten in der Liste der 6 Farben aus oder oben in dem Farbübergangsmuster?

Wenn du unten auswählst, müsste es eigentlich alles richtig von selbst gehen. 
Wenn du oben auswählst, dann kann er die Vordergrundfarbe  (derzeit) nicht entsprechend anpassen.

**Comment by AndiWebred** [comment]
ja, so gehts! kam die auswahl der sechs farben unten neu dazu? hab ich wohl übersehen, sorry. ticket kann dann wegen mir geschlossen werden.
