### ISSUE TITLE
Feature request color legend

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-calendar#95]
Feature request:

"is there a way to display the different calendar thread names inside the calendar"

Aus Helpdesk. Empk.
Ob man die Kalender-Feeds zum Beispiel über eine Farblegende oder über eine andere Lösung darstellen kann.

z.B.:
grün = Institut für XYZ
rot = Seminar-Feed 

(evtl. auch einfach durch Tags mit den entsprechenden Feldnamen, wenn man ein Attribut im Shortcode hinterlegt).

**Comment by xwolfde** [comment]
Ich glaub das geht in eine falsche Richtung: Die Farben sollen ein rein optischen Effekt haben, aber keinen informativen. Denn Farben könne auch je nach Ausgabeoknfiguration "aus" sein oder vom Menschen nicht erkannt werden.
Daher gehören Informationen darüber, in welcher Kategorie ein Artikel gehört, eher in der Textanzeige/Auszug des Events.
Von daher könnte eine denkbare Lösung die sein, dass man bei der Ausgabe der Termine die "Kategorie" als Text mit dabei angibt:
Die Farben werden jetzt ja als Kategorie des Feeds angegeben.

**Comment by xwolfde** [comment]
Ref #43

**Comment by xwolfde** [comment]
Das Plugin wird wahrscheinlich nicht mehr weiterentwickelt werden.
Wir werden stattdessen das Plugin The Events Calendar lizensieren. Eine Bereitstellung von The Events Calendar ist ab Februar geplant. Wir müssen jedoch zunächst noch eine Vorarbeiten leisten.
In der Webmaster-Sprechstunde am 2.2. hoffen wir nähere Informationen geben zu können.
